version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          working_directory: cypress-tests
          command: |
            npm install
            npm run cypress:run --START_URL=${START_URL} --RECORD_KEY=${RECORD_KEY}
