version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          working_directory: ~/circle-cypress-test/cypress-tests
          command:npm install && npx cypress run
